language: node_js
services:
  - mongodb
  - redis-server
node_js:
  - '8'
env:
  - FOLDER=client
  - FOLDER=server
before_script:
  - cd server && sudo apt-get install libldap2-dev -y && npm install && npm run init:db
script: 
  - cd .. && cd $FOLDER && npm install && npm run test
